Feature/consensus state
forbole/big-dipper-default-ui pull request #23
Opened 2020-11-27 09:24 UTC by YuhsinLiao1995

## Description
build Consensus State component
closes #6 

## Checklist
- [v] Ran Linting
- [v] Targeted PR against correct branch.
- [v] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [v] Wrote unit tests.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [v] Re-reviewed `Files changed` in the Github PR explorer.

2020-11-30 02:13 UTC, ryuash requested changes
Overall good improvement, I still see some questionable divs being created here and there and the CSS could use a bit more work but it's not bad. 

One small issue i currently have is you only allow users to target what you want them to target. EX - I have no easy way of editing `classes.container` `classes.chartBox` `classes.boxFlexible`. In the future we can also improve on the classes naming convention a bit more. It's currently confusing and not at all description.

If we look at material ui component classes for example, we can read the classnames and know exactly what it does. ex- we know it's part of the Paper component because it starts with `MuiPaper` followed by a short description of what this class does.
![image](https://user-images.githubusercontent.com/42913823/100561336-a31d9a00-32f3-11eb-918a-93d4ea46f6dc.png)

Another example would be semantic, though not as description and unique as material, just by reading the classname i know what it does


![image](https://user-images.githubusercontent.com/42913823/100561483-04de0400-32f4-11eb-84e5-5e6d96a9f8f1.png)

Last would be our own components, even less description but I think it does the job in showing a little bit goes a long way in having good naming conventions
![image](https://user-images.githubusercontent.com/42913823/100561569-3787fc80-32f4-11eb-83d4-fb994aa6e0be.png)

-------------------
Also it's `assets` not `assests` can you rename the `stories/assests` folder

2020-11-30 06:43 UTC, YuhsinLiao1995 commented on src/components/consensus_state/styles.tsx
> +      width: '100%',
i removed width: '100%' in root instead

2020-11-30 11:55 UTC, ryuash requested changes
.

2020-12-01 06:47 UTC, ryuash approved these changes

2020-12-01 06:49 UTC, merged